title: Outreach
description: Responsible for helping developers who use AMP to remain productive and keeping the AMP community healthy. This includes maintaining and enhancing AMP's developer-facing sites and documentation, maintaining communication channels, organizing community events, etc.
facilitator:
  login: pbakaus
  name: Paul Bakaus
members:
  - login: pbakaus
    name: Paul Bakaus
  - login: CrystalOnScript
    name: Crystal Lambert
  - login: morsssss
    name: Ben Morss
  - login: mrjoro
    name: Joey Rozier
  - login: sebastianbenz
    name: Sebastian Benz
  - login: alankent
    name: Alan Kent
  - login: mattludwig
    name: Matt Ludwig
  - login: uskay
    name: Yusuke Utsonomiya
